### ISSUE TITLE
Using deprecated api that is about to be removed

### ISSUE THREAD

**Issue by vadali** [TheClimateCorporation/lemur#36]
Hey,
I just received an email from AWS warning us to stop using `DescribeJobFlows` api call:

> Based on our current records, you are currently using one of our deprecated API (DescribeJobFlows) to get the details for all of your EMR clusters.
> 
> Starting Midnight (24:00 UTC) 12/14/2015, we will require users to move to the new set of APIs. The newer set of APIs provide a much more granular and low latency access.
> 
> Here is the list of new APIs:
> 
> ListClusters, DescribeCluster, ListSteps, ListInstanceGroups and ListBootstrapActions instead.
> 
> API Documentation: http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_Operations.html
> 
> DescribeJobFlows API Doc: http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeJobFlows
> 
> FAQ:
> 
> Q. WHY THIS IS REQUIRED?
> A. DescribeJobFlows API is deprecated more than a year ago.
> 
> Q. WHAT DO I HAVE TO DO?
> A. Make sure you are not using DescribeJobFlows API. If you are using make code changes to use ListClusters, DescribeCluster, ListSteps, ListInstanceGroups and ListBootstrapActions instead.
> 
> Q. HOW SOON DOES THIS NEEDS TO GET ADDRESSED?
> A. This work needs to be completed by 12/14/2015.
> 
> Best regards,
> EMR Service Team

I found that this call appears in two functions: `flow-for-name` and `job-flow-detail`. I hope I will get around to fixing that soon.

Thanks,
Shlomi

**Comment by phrend** [comment]
Yup - we need this update as well!

**Comment by shlomiv** [comment]
this seems to be working fine after 20a74c00f52746837c0eb3503f3667fe08d4f039 , closing.
